// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKCVCgclWT-_FGEq6Bd9sZ2J7J3_7-fjE',
    appId: '1:908038441537:web:0cedf3b32f978ac405d4c0',
    messagingSenderId: '908038441537',
    projectId: 'weighing-bridge-63769',
    authDomain: 'weighing-bridge-63769.firebaseapp.com',
    storageBucket: 'weighing-bridge-63769.firebasestorage.app',
    measurementId: 'G-T88K7YR6SX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWShJMCWWIlfmCNSoIYD1e36Tck7-snEs',
    appId: '1:908038441537:ios:4bdb1f95de1acdda05d4c0',
    messagingSenderId: '908038441537',
    projectId: 'weighing-bridge-63769',
    storageBucket: 'weighing-bridge-63769.firebasestorage.app',
    iosBundleId: 'com.example.weighingBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKCVCgclWT-_FGEq6Bd9sZ2J7J3_7-fjE',
    appId: '1:908038441537:web:d86ea42942ceac4605d4c0',
    messagingSenderId: '908038441537',
    projectId: 'weighing-bridge-63769',
    authDomain: 'weighing-bridge-63769.firebaseapp.com',
    storageBucket: 'weighing-bridge-63769.firebasestorage.app',
    measurementId: 'G-3L29KT7R16',
  );

}